name: Greeting from Rabindar KUMAR
on: [push, pull_request]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Rabindar
        LAST_NAME: KUMAR
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
